// Gerado por tauri-specta a partir de src-tauri/src/lib.rs. Não edite à mão: rode `bun run gen:bindings`.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Pasta onde está o executável do app. Os sidecars (yt-dlp, ffmpeg, ffprobe, deno)
	 *  são copiados para cá na instalação, e o yt-dlp recebe isso em --ffmpeg-location.
	 */
	binDir: () => typedError<string, string>(__TAURI_INVOKE("bin_dir")),
	/**
	 *  Encerra o yt-dlp e os processos que ele abriu (ffmpeg, ffprobe, deno).
	 *  O kill do plugin shell só alcança o yt-dlp, e o ffmpeg continuaria escrevendo na pasta.
	 */
	killTree: (pid: number) => typedError<null, string>(__TAURI_INVOKE("kill_tree", { pid })),
	/**
	 *  Rodando de dentro de um AppImage? Lá os sidecars ficam num sistema de arquivos
	 *  só de leitura, então `yt-dlp -U` sempre falharia; o yt-dlp novo vem com a
	 *  atualização do app.
	 */
	isAppimage: () => __TAURI_INVOKE<boolean>("is_appimage"),
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

