// Gerado por tauri-specta a partir de src-tauri/src/lib.rs. Não edite à mão: rode `bun run gen:bindings`.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Pasta onde está o executável do app. Os sidecars (yt-dlp, ffmpeg, ffprobe, deno)
	 *  são copiados para cá na instalação, e o yt-dlp recebe isso em --ffmpeg-location.
	 */
	binDir: () => typedError<string, string>(__TAURI_INVOKE("bin_dir")),
	/**
	 *  Encerra o yt-dlp e os processos que ele abriu (ffmpeg, ffprobe, deno).
	 *  O kill do plugin shell só alcança o yt-dlp, e o ffmpeg continuaria escrevendo na pasta.
	 */
	killTree: (pid: number) => typedError<null, string>(__TAURI_INVOKE("kill_tree", { pid })),
	/**
	 *  Rodando de dentro de um AppImage? Lá os sidecars ficam num sistema de arquivos
	 *  só de leitura, então `yt-dlp -U` sempre falharia; o yt-dlp novo vem com a
	 *  atualização do app.
	 */
	isAppimage: () => __TAURI_INVOKE<boolean>("is_appimage"),
	platform: () => __TAURI_INVOKE<Platform>("platform"),
	engineStart: (request: DownloadRequest, onEvent: Channel<EngineEvent>) => typedError<null, EngineError>(__TAURI_INVOKE("engine_start", { request, onEvent })),
	engineCancel: (id: string) => typedError<boolean, EngineError>(__TAURI_INVOKE("engine_cancel", { id })),
	engineUpdate: () => typedError<UpdateResult, EngineError>(__TAURI_INVOKE("engine_update")),
	engineVersion: () => typedError<string, EngineError>(__TAURI_INVOKE("engine_version")),
	/**  Abre o arquivo baixado no app que o usuário escolher (Android). */
	engineOpen: (uri: string) => typedError<null, EngineError>(__TAURI_INVOKE("engine_open", { uri })),
	/**
	 *  Inscreve a tela para receber textos compartilhados por outros apps. O que chegou
	 *  antes da inscrição (app aberto pelo próprio compartilhamento) é entregue na hora.
	 */
	engineWatchShared: (onShared: Channel<SharedText>) => typedError<null, EngineError>(__TAURI_INVOKE("engine_watch_shared", { onShared })),
};

/* Types */
/**  Um download: identificador (para cancelar), link e os argumentos do yt-dlp já montados pela tela. */
export type DownloadRequest = {
	id: string,
	url: string,
	args: string[],
};

export type EngineError = 
/**  Este motor não existe nesta plataforma. */
{ kind: "unsupported" } | 
/**  Falha na ponte com o plugin nativo ou dentro dele. */
{ kind: "bridge"; message: string };

/**
 *  O que chega pelo canal durante um download: uma linha do yt-dlp ou o fim.
 *  `code` nulo quer dizer que o processo não terminou sozinho (cancelado).
 */
export type EngineEvent = { kind: "line"; text: string; stream: Stream } | 
/**  O arquivo pronto foi publicado num lugar que o usuário vê (Android: Downloads/BaixaVideo). */
{ kind: "saved"; uri: string; name: string } | { kind: "exit"; code: number | null };

export type Platform = "desktop" | "android";

/**  Texto que outro app compartilhou com este (Android: menu "Compartilhar"). */
export type SharedText = {
	text: string,
};

export type Stream = "stdout" | "stderr";

export type UpdateResult = {
	status: UpdateStatus,
	version: string,
};

export type UpdateStatus = "done" | "alreadyUpToDate";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

